name: CI/CD to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and Test
        run: |
          chmod +x ./build.sh
          ./build.sh
          chmod +x ./test.sh
          ./test.sh

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.rakeshh729 }}
          password: ${{ secrets.dckr_pat_Qqia8bHfFR1MPesU1KGbxCXVdz4 }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: rakeshh729/fusionpact-devops-challenge:${{ github.sha }}

