name: CI/CD to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: rakeshy977/fusionpact-devops-challenge:${{ github.sha }}
          
      - name: Deploy Frontend to EC2 via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            docker stop frontend || true
            docker rm frontend || true
            # Force-kill processes on 80 (optional, only if above doesn't work)
            sudo fuser -k 80/tcp || true

            docker pull rakeshy977/frontend:latest
            docker run -d --name frontend -p 8081:80 rakeshy977/frontend:latest

      - name: Deploy Backend to EC2 via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            docker stop backend || true
            docker rm backend || true
            sudo fuser -k 5000/tcp || true

            docker pull rakeshy977/fusionpact-devops-challenge:latest
            docker run -d --name backend -p 5000:5000 rakeshy977/fusionpact-devops-challenge:latest

      - name: Deploy Prometheus to EC2 via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            docker stop prometheus || true
            docker rm prometheus || true
            docker pull prom/prometheus:latest
            docker run -d --name prometheus -p 9090:9090 prom/prometheus:latest

      - name: Deploy Grafana to EC2 via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            docker stop grafana || true
            docker rm grafana || true
            docker pull grafana/grafana:latest
            docker run -d --name grafana -p 3000:3000 grafana/grafana:latest
